class FeatureFlagTestGenerator < TestGenerator
  def self.generate
    project_root = Pathname.new File.expand_path "..", __dir__

    project_root.glob "feature_flags/*.yml" do |file|
      generator = new project_root, file
      generator.generate
    end
  end

  def initialize project_root, input_filename
    @project_root = project_root
    @input_filename = input_filename
    @test_case = YAML.safe_load File.read input_filename
  end

  def definition
    @test_case["definition"]
  end

  private

  def language_settings
    {
      elixir: {
        filename_template: "%s_test.exs",
        template: <<~TEMPLATE
          # AUTOGENERATED FILE - DO NOT EDIT
          defmodule Riddler.<%= class_name %>Test do
            use ExUnit.Case, async: false
            @moduletag :spec

            setup_all do
              %{definition: <%= elixir_hash definition %>}
            end
          <% tests.each do |test| %>
            test "<%= test["name"] %>", context do
              riddler_context = <% if test["context"].nil? %>nil<% else %><%= elixir_hash test["context"] %><% end %>
              expected_result = <% if test["result"].nil? %>nil<% else %><%= test["result"] %><% end %>

              result = Riddler.render context[:definition], riddler_context
              assert expected_result == result
            end
          <% end %>
          end
        TEMPLATE
      },
      ruby: {
        filename_template: "test_%s.rb",
        template: <<~TEMPLATE
          # AUTOGENERATED FILE - DO NOT EDIT
          require "helper"

          class <%= class_name %>Test < ::Minitest::Test
            attr_reader :definition

            def setup
              @definition = <%= definition %>
            end
          <% tests.each do |test| %>
            def test_<%= test["name"] %>
              context = <% if test["context"].nil? %>nil<% else %><%= test["context"] %><% end %>
              expected_result = <% if test["result"].nil? %>nil<% else %><%= test["result"] %><% end %>

              result = ::Riddler.render definition, context
              assert_equal expected_result, result
            end
          <% end %>
          end
        TEMPLATE
      }
    }
  end
end
